---
services:
  can-i-charge:
    image: boosterl/can-i-charge:dev
    container_name: can-i-charge
    environment:
      - API_KEY=<your-api-key>
      - STATIONS=471003
      - EXPORTER=true
      # - EXPORTER_PORT="9041"
      # - EXPORTER_INTERVAL="120"
    ports:
      - 9041:9041
